# This was a difficult problem, because I had to copy and paste each entry into the variable set as DNA_sample then I had a probelm with
# The newline characters
# Then finally I saw they wanted to the sixth signicant figure


# This is the sample taken from the notepad 
DNA_sample = """GATTGCGGCAATAGTTATGGGGGTATACTCCGTCACCACGGCGCTGTACTCCATGCGTTC
CAAACCCACCGAAGTGCGAGTTTTGGTTAGTAGGATCGTATTGCGGGCCGGTAGTATTGA
AACGAAAGTGACACCAGTCCGCAGGTCCCACCCCCACGAACAACTCCCCCCCCCAGCAAA
TGCGATGTACTACTTGAAATTAAATGGCGGTCACTTTGCCCTACAGGATGACGGGTTACA
GGGCTGATAACGGCTTAAATTCTAAGTGAGCTGGGTGGCTTATTCTCAAAACACTAAACT
TGAGTAGACTCAACACTCTGAGGGATCTCCTGCCGCACCGATTTCGAGCATGTGGGGATT
AGGAGCTTTACAGGTTCGGGCGGCTTGTACATGACCAGGAGATGCAGAGGTGACGCGAGA
GTACGCAGTCCACATGACAAGCCAATCTCGTGATGGGTTGTCTACTGGATTATGCGAGCC
TTTTCATGAATCTGGACCAGGACCAGTTAATTAGGATGTAACGTCTGGGGTTCGGTGTGG
ACGCGATGGTTCTAGGCGGGCTGGGTTGTGTAACCTGGTCAGATACTATAATCCAACTTG
CCTTCTCAAGTTGCTCTTCGTGATCACTAGTCAGTTGAGTGCGACTAATCCAACTGGTGG
CTTGGATCTGGCGGCCAACACGCATGAGGCTCAGCGACCCTCTTCCCGCCGTAGCTGACG
AAGAGCGCTGGTGGCGCAGATGTTTCGCGCCCGACTTACCCGTGTATCGCCCTAAGCATT
CGTCTCGGAAACGAGGGAGTCGAAAAATAGGTGCCCGGAAGCTTTAGCATGCAAGTGGAA
AAAAGGCTCTTGTGAAGGTACCATAGTTAGGACCATAGCGAACACTGCGATACCAACCCC
CGAGTG"""

def calculate_gc_content(DNA_sample):
    # Remove newline characters from the DNA sample
    DNA_sample = DNA_sample.replace('\n', '')
    gc_count = 0
    total_bases = len(DNA_sample)

    for base in DNA_sample:
        if base in "GCgc":
            gc_count += 1

    gc_content = (gc_count / total_bases) * 100
    return gc_content

gc_content = calculate_gc_content(DNA_sample)
# Format the output to three decimal places
# This Is for the sixth figure
print(f"{gc_content:.6f}%")
